#!/bin/bash

# Autobuild the Image on Docker Hub with advanced options and buildx for multiarch images
# read more: https://github.com/Tob1asDocker/dockerhubhooksexample

# '--push' shorthand for '--output=type=registry'

set -ex

echo "### RUN build START: using buildx ###"
echo "Image Name: ${IMAGE_NAME} (Repo: ${DOCKER_REPO}, Tag: ${DOCKER_TAG})"
echo "Dockerfile Path/Name: ${DOCKERFILE_PATH}"
BUILDPLATFORM="${BUILDPLATFORM:-"linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"}"
echo "Architectures=${BUILDPLATFORM}"

docker buildx build --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --build-arg VCS_REF="$(git rev-parse --short HEAD)" --tag "${IMAGE_NAME}" --platform "${BUILDPLATFORM}" --file "${DOCKERFILE_PATH}" --push .

echo "### RUN build END"
