# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#

# See also https://stackoverflow.com/questions/45517733/how-to-publish-docker-images-to-docker-hub-from-gitlab-ci

docker-build-figlet:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    CI_REGISTRY_IMAGE: '$CI_REGISTRY/dockerfornovices/figlet'
    DOCKERFILE: "Figlet/Dockerfile"
    DEFAULT_TAG: "1.0"
    DOCKER_BUILD_CONTEXT: /dev/null
  rules:
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
       changes:
       - ${DOCKERFILE}
       - .gitlab-ci.yml
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - echo Building Image $CI_REGISTRY_IMAGE
    - docker image build --pull --tag "${CI_REGISTRY_IMAGE}:${DEFAULT_TAG}" -f $DOCKERFILE $DOCKER_BUILD_CONTEXT 
    - docker image tag "${CI_REGISTRY_IMAGE}:${DEFAULT_TAG}" "${CI_REGISTRY_IMAGE}:latest"
    - docker image push --all-tags "$CI_REGISTRY_IMAGE"

docker-build-api-server:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    CI_REGISTRY_IMAGE: '$CI_REGISTRY/dockerfornovices/api-server'
    GO_VERSION: "1.14"
    DEFAULT_TAG: ${GO_VERSION}
    BUILD_ARGS: '--build-arg GO_VERSION=$GO_VERSION'
    DOCKERFILE: "FileSetA/Dockerfile"
    DOCKER_BUILD_CONTEXT: FileSetA
  rules:
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
       changes:
       - ${DOCKERFILE}
       - .gitlab-ci.yml
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - echo Building Image $CI_REGISTRY_IMAGE
    - docker image build --pull --tag "${CI_REGISTRY_IMAGE}:${DEFAULT_TAG}" $BUILD_ARGS -f $DOCKERFILE $DOCKER_BUILD_CONTEXT 
    - docker image tag "${CI_REGISTRY_IMAGE}:${DEFAULT_TAG}" "${CI_REGISTRY_IMAGE}:latest"
    - docker image push --all-tags "$CI_REGISTRY_IMAGE"
