# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#

# See also https://stackoverflow.com/questions/45517733/how-to-publish-docker-images-to-docker-hub-from-gitlab-ci

docker-build-figlet:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  rules:
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
       changes:
       - Figlet/Dockerfile
       - .gitlab-ci.yml
  variables:
    CI_REGISTRY_IMAGE: '$CI_REGISTRY/dockerfornovices/figlet'
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - echo Running on default branch '$CI_DEFAULT_BRANCH:' $CI_REGISTRY_IMAGE
    - docker image build --pull --tag "${CI_REGISTRY_IMAGE}:1.0" - < Figlet/Dockerfile
    - docker image tag "${CI_REGISTRY_IMAGE}:1.0" "${CI_REGISTRY_IMAGE}:latest"
    - docker image push --all-tags "$CI_REGISTRY_IMAGE"
