#!/usr/bin/env bash

# This material is free software for demonstration purposes only.

# Copyright (c) 2018 Alec Clews <alecclews@gmail.com>
#
#
# Use of this source code is governed by an MIT license.
# See the project's LICENSE file for more information.

# Setup local docker envirobment to start the talk

docker container rm -f myAlpine nginx myJDK

docker image rm alpine jdk

docker image pull nginx
