name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  api-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  FileSetA
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          working-directory:  FileSetA
          push: true
          tags: dockerfornovices/api-server
