name: sqlite

on:
  workflow_dispatch:
  push:
    paths:
    - FileSetC/**
    - .github/workflows/sqlite.yml
    branches:
     - 'main'

jobs:
  api-server:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context:  "{{defaultContext}}:FileSetC"
          push: true
          platforms: linux/amd64, linux/arm64
          tags: dockerfornovices/sqlite:latest, dockerfornovices/sqlite:0.1
